version: '3.8'

services:
  web:
    build: .
    ports:
      - "5052:5052"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=audio_to_text.settings
    volumes:
      - .:/app
    restart: unless-stopped 